server:
  port: 9003

spring:
  application:
    name: order-service
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cs504
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  cloud:
    stream:
      bindings:
        output: payments
