server:
  port: 9003

spring:
  application:
    name: shopping-cart-service
  datasource:
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cs504
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  cloud:
    stream:
      bindings:
        output: payments-todo
        input: payments-done

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/